server:
  port: 8080
  host: "0.0.0.0"
health:
  web-context: "/health"
  enabled: true
  checks:
    heapMemory:
      thresholdPercent: 98.0
    diskSpace:
      path: "."
      thresholdPercent: 98.0
metrics:
  web-context: "/metrics"
  enabled: true
tracing:
  components:
    web-server:
      spans:
        - name: "HTTP Request"
          enabled: true
        - name: "content-read"
          enabled: false
        - name: "content-write"
          enabled: false
  paths:
    - path: "/health"
      enabled: false
    - path: "/health/ready"
      enabled: false
    - path: "/health/live"
      enabled: false
    - path: "/metrics"
      enabled: false